# application: newproject
runtime: python27
threadsafe: false
api_version: 1

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /newproject
  static_dir: /newproject


  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.

  # Site root
- url: /.*
  static_files: templates/index.html
  upload: templates/index.html

  # Take access to static file

- url: /.*
  script: main.py

- url: /.*
  static_files: static/style.css
  upload: static/style.css

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto